/*Copyright (c) 2017-2018 us.ibm.com All Rights Reserved.
 This software is the confidential and proprietary information of us.ibm.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with us.ibm.com*/

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

@TypeDefs({@TypeDef(name = "DateTime",
                     defaultForType = org.joda.time.LocalDateTime.class,
                     typeClass = com.wavemaker.commons.data.type.WMPersistentLocalDateTime.class)})
package com.hrdb;

import org.hibernate.annotations.TypeDefs;
import org.hibernate.annotations.TypeDef;

